POST http://localhost:9000/api/v1/user/login
Content-Type: application/json

{
  "name": "1123a1",
  "password": "123"
}
###
POST http://localhost:9000/api/v1/user/register
Content-Type: application/json

{
"name": "1123a1",
"password": "123"
}

###
POST http://localhost:9000/api/v1/cart/add
Content-Type: application/json

{
  "sku_id": "13131",
  "quantity": 13131,
  "uid": "afdsakflsjfl"
}

###

POST http://localhost:9000/api/v1/cart/mget
Content-Type: application/json

{
  "page_size": "1",
  "page_num": 10,
  "uid": "930fbafc-f9ed-458f-a1cf-768d65f8825e"
}

###

GET http://localhost:9000/api/v1/user/get/f9c7ca1b-7995-4df4-bb2f-7b741feaae31
###
GET http://localhost:9000/api/v1/home/category/head
###
GET http://localhost:9000/api/v1/main/get_sku/261311

###
WEBSOCKET ws://localhost:9000/api/v1/im/ws
Content-Type: application/json

{
  "message": "test"
}
###
GET http://localhost:9000/api/v1/im/receiver/mget?uid=930fbafc-f9ed-458f-a1cf-768d65f8825e

###
POST http://localhost:9000/api/v1/im/history/get_one
Content-Type: application/json

{
  "sender_id": "930fbafc-f9ed-458f-a1cf-768d65f8825e",
  "receiver_id": "33633d8f-b368-46b3-827d-d316af78f9a4"
}